[package]
name = "Auction"
version = "0.0.0"

[addresses]
deploy_address = "0xaaaa"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet" }
Library = { local = "../../../../Library/move" }